name: Selenium Tests

on:
  push:
    branches: [swag_labs]
  pull_request:
    branches: [swag_labs]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Choose which test suite to run'
        type: choice
        options:
          - all
          - smoke
        default: all

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Build project without tests
        run: mvn clean install -DskipTests

      - name: Run tests
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.test_suite }}" == "smoke" ]]; then
              mvn test -Dgroups=smoke
            else
              mvn test
            fi
          else
            mvn test
          fi

      - name: Upload test reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports/
          retention-days: 30
